final Map datos = {
  'datos_personales': {
    0: 'Nombre',
    1: 'Estado Civil',
    2: 'Registro Federal de Contribuyentes(RFC)',
    3: 'Clave única de Registro de Población (CURP)',
    4: 'Lugar de nacimiento',
    5: 'Fecha de nacimiento',
    6: 'Nacionalidad',
    7: 'Domicilio',
    8: 'Teléfono particular',
    9: 'Teléfono celular',
    10: 'Correo electrónico',
    11: 'Edad',
    12: 'Fotografía',
    13: 'Señas particulares',
    14: 'Tipo de sangre',
    15: 'Puesto o cargo que desempeña',
    16: 'Domicilio de trabajo',
    17: 'Correo electrónico institucional',
    18: 'Teléfono institucional',
    19: 'Referencias laborales',
    20: 'Información generada durante los procesos de reclutamiento, selección y contratación',
    21: 'Capacitación laboral',
    22: 'Trayectoria educativa',
    23: 'Títulos',
    24: 'Cédula profesional',
    25: 'Certificados',
    26: 'Reconocimientos',
    27: 'Datos de identificación',
    28: 'Datos de contacto',
    29: 'Datos académicos',
  }
};
